-- Run this in the Supabase SQL Editor (Dashboard -> SQL -> New query)

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  title text not null default '',
  content text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists notes_updated_at_idx on public.notes (updated_at desc);

create or replace function public.set_notes_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists notes_set_updated_at on public.notes;
create trigger notes_set_updated_at
before update on public.notes
for each row
execute function public.set_notes_updated_at();

-- Backend uses the service_role key (bypasses RLS).
-- These policies are for safety if you ever use the anon key from a client.
alter table public.notes enable row level security;

drop policy if exists "Allow all notes access" on public.notes;
create policy "Allow all notes access"
on public.notes
for all
using (true)
with check (true);
